### ISSUE TITLE
SQLITE_CANTOPEN on start

### ISSUE THREAD

**Issue by cleverdumb** [coding-heads/JSM-Pastebin#19]
![Screenshot 2022-11-05 at 3 27 13 PM](https://user-images.githubusercontent.com/97397944/200127549-fedc7f82-7fb6-494d-82cd-fc5895152405.png)
this appears when i run the server.js
i installed all the node modules already.
not sure did i do anything wrong
happens when i load in the localhost server

**Comment by Thenlie** [comment]
> this appears when i run the server.js i installed all the node modules already. not sure did i do anything wrong happens when i load in the localhost server

have you ever used SQLite locally before? You may need to install it globally on your machine. @brandonetter and I are also looking into possible pathing issues due to OS differences.

**Comment by cleverdumb** [comment]
yes, now it worked somehow :)
